package chess.pgn;

public enum Type {
	STRING, INTEGER, PERIOD, ASTERISK, LEFT_BRACKET, RIGHT_BRACKET, LEFT_PAREN, RIGHT_PAREN, LEFT_ANGLE, RIGHT_ANGLE, LEFT_BRACE, RIGHT_BRACE, NAG, DOLLAR_SIGN, SYMBOL, WHITE_SPACE, QUOTE, DIGIT, LETTER, UNDERSCORE, PLUS, HASH, EQUAL, COLON, HYPHEN, BACKSLASH, PRINTING_CHAR, COMMENT 
}
